# Generated by Django 4.1.5 on 2023-01-16 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assychild',
            name='assy_id',
        ),
        migrations.RemoveField(
            model_name='assychild',
            name='child_id',
        ),
        migrations.RemoveField(
            model_name='bom',
            name='child_id',
        ),
        migrations.RemoveField(
            model_name='bom',
            name='operation_id',
        ),
        migrations.RemoveField(
            model_name='bom',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='bor',
            name='matl_id',
        ),
        migrations.RemoveField(
            model_name='bor',
            name='ope_id',
        ),
        migrations.RemoveField(
            model_name='bor',
            name='resource_id',
        ),
        migrations.RemoveField(
            model_name='mask',
            name='child_id',
        ),
        migrations.RemoveField(
            model_name='mask',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='ope',
            name='matl_id',
        ),
        migrations.RemoveField(
            model_name='ope',
            name='out_id',
        ),
        migrations.DeleteModel(
            name='Assy',
        ),
        migrations.DeleteModel(
            name='AssyChild',
        ),
        migrations.DeleteModel(
            name='Bom',
        ),
        migrations.DeleteModel(
            name='Bor',
        ),
        migrations.DeleteModel(
            name='Mask',
        ),
        migrations.DeleteModel(
            name='Matl',
        ),
        migrations.DeleteModel(
            name='Ope',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
